/*
 * gpio.c
 *
 *  Created on: 27-Nov-2025
 *      Author: skani
 */

#include "rcc.h"
#include "gpio.h"

void GPIO_Init ()
{
	RCC.AHB1ENR.GPIODEN = RCC_ENABLE;

	GPIOD.MODER.PIN12 = GPIO_MODE_OUTPUT;
	GPIOD.MODER.PIN13 = GPIO_MODE_OUTPUT;
	GPIOD.MODER.PIN14 = GPIO_MODE_OUTPUT;
	GPIOD.MODER.PIN15 = GPIO_MODE_OUTPUT;

	GPIOD.OSPEEDR.PIN12 = GPIO_SPEED_LOW;
	GPIOD.OSPEEDR.PIN13 = GPIO_SPEED_LOW;
	GPIOD.OSPEEDR.PIN14 = GPIO_SPEED_LOW;
	GPIOD.OSPEEDR.PIN15 = GPIO_SPEED_LOW;
}
